export const PERSIST = 'persist/REHYDRATE';
export const REQUEST_PLAID_ACCESS_TOKEN = "REQUEST_PLAID_ACCESS_TOKEN";
export const REQUEST_PLAID_ACCESS_TOKEN_SUCCESS = "REQUEST_PLAID_ACCESS_TOKEN_SUCCESS";
export const REQUEST_PLAID_ACCESS_TOKEN_FAILURE = "REQUEST_PLAID_ACCESS_TOKEN_FAILURE";
export const LOAD_FOOTPRINT = "LOAD_FOOTPRINT";
export const LOAD_FOOTPRINT_SUCCESS = "LOAD_FOOTPRINT_SUCCESS";
export const LOAD_FOOTPRINT_FAILURE = "LOAD_FOOTPRINT_FAILURE";
